name = "QuantumGradientGenerators"
uuid = "a563f35e-61db-434d-8c01-8b9e3ccdfd85"
authors = ["Michael Goerz <mail@michaelgoerz.net"]
version = "0.1.0-dev"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"

[compat]
QuantumPropagators = ">=0.3.0"
julia = "1.6"
