name = "QuantumGradientGenerators"
uuid = "a563f35e-61db-434d-8c01-8b9e3ccdfd85"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.1.4+dev"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuantumControlBase = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = "1"
QuantumControlBase = "0.8,0.9"
Random = "1"
SparseArrays = "1"
julia = "1.9"
